### ISSUE TITLE
min SDK too high

### ISSUE THREAD

**Issue by uishon** [danysantiago/sendgrid-android#2]
I'd like to use the library but I've got minSDK=11 and the library has its minSDK set to 16. I can override that in the Manifest.xml, but is there a reason for this limit? I guess - if there's a reason - overriding this in the Manifest.xml won't help me and I will end up with an issue... Thanks.

**Comment by danysantiago** [comment]
Hey uishon,

There is no immediate reason for the minSdk to be 16, when I uploaded the library that was the relevant minSdk at the time. As of today API lvl 16 is less than 10% based on the dashboards. See http://developer.android.com/about/dashboards/index.html.

However, if you need to support lower apis please, feel free to bump down the sdk version, hopefully you won't run into any problem since the library barely uses any Android apis.

**Comment by uishon** [comment]
Thanks. I'm currently running it via changing the manifest and it's working well. Will let you know if I run into an issue.

**Comment by danysantiago** [comment]
Great, closing this issue then.
